### ISSUE TITLE
Can't make on Pop!_os

### ISSUE THREAD

**Issue by boliwiz** [jafarlihi/connmap#1]
I probable need some dependencies but I can't figure out which one.

System info:
OS: Pop!_OS 19.10 x86_64
Kernel: 5.3.0-7642-generic

I already installed:
`libghc-diagrams-cairo-dev`
`libx11-dev`

Error:
`% make install
                                                                                                                
mkdir -p ./build
gcc -std=gnu11 -I./includes -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo -lX11 -O0 -c sources/ss.c -o build/ss.o
gcc -std=gnu11 -I./includes -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo -lX11 -O0 -c sources/x11.c -o build/x11.o
gcc -std=gnu11 -I./includes -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo -lX11 -O0 -c sources/cairo.c -o build/cairo.o
gcc -std=gnu11 -I./includes -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo -lX11 -O0 -c sources/config.c -o build/config.o
gcc -std=gnu11 -I./includes -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo -lX11 -O0 -c sources/geo.c -o build/geo.o
gcc -std=gnu11 -I./includes -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo -lX11 -O0 -c sources/main.c -o build/main.o
gcc -std=gnu11 -I./includes -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo -lX11 -O0 -c sources/ip.c -o build/ip.o
gcc -std=gnu11 -I./includes -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo -lX11 -O0 ./build/ss.o ./build/x11.o ./build/cairo.o ./build/config.o ./build/geo.o ./build/main.o ./build/ip.o -o connmap.exe
/usr/bin/ld: ./build/x11.o: in function `initX11':
x11.c:(.text+0x40): undefined reference to `XOpenDisplay'
/usr/bin/ld: x11.c:(.text+0xe6): undefined reference to `XCreateColormap'
/usr/bin/ld: x11.c:(.text+0x1ba): undefined reference to `XCreateWindow'
/usr/bin/ld: x11.c:(.text+0x1de): undefined reference to `XLowerWindow'
/usr/bin/ld: x11.c:(.text+0x1f7): undefined reference to `XMapWindow'
/usr/bin/ld: ./build/cairo.o: in function `cairo_close_x11_surface':
cairo.c:(.text+0x18): undefined reference to `cairo_xlib_surface_get_display'
/usr/bin/ld: cairo.c:(.text+0x28): undefined reference to `cairo_surface_destroy'
/usr/bin/ld: cairo.c:(.text+0x34): undefined reference to `XCloseDisplay'
/usr/bin/ld: ./build/cairo.o: in function `draw_world':
cairo.c:(.text+0x72): undefined reference to `cairo_create'
/usr/bin/ld: cairo.c:(.text+0x98): undefined reference to `cairo_set_source_rgba'
/usr/bin/ld: cairo.c:(.text+0xa7): undefined reference to `cairo_paint'
/usr/bin/ld: cairo.c:(.text+0x13d): undefined reference to `cairo_image_surface_create_from_png'
/usr/bin/ld: cairo.c:(.text+0x165): undefined reference to `cairo_set_source_surface'
/usr/bin/ld: cairo.c:(.text+0x174): undefined reference to `cairo_paint'
/usr/bin/ld: cairo.c:(.text+0x183): undefined reference to `cairo_destroy'
/usr/bin/ld: ./build/cairo.o: in function `draw_point':
cairo.c:(.text+0x1c1): undefined reference to `cairo_create'
/usr/bin/ld: cairo.c:(.text+0x1e1): undefined reference to `cairo_set_source_rgba'
/usr/bin/ld: cairo.c:(.text+0x1ed): undefined reference to `cairo_paint'
/usr/bin/ld: cairo.c:(.text+0x229): undefined reference to `cairo_set_source_rgba'
/usr/bin/ld: cairo.c:(.text+0x241): undefined reference to `cairo_set_line_width'
/usr/bin/ld: cairo.c:(.text+0x28b): undefined reference to `cairo_arc'
/usr/bin/ld: cairo.c:(.text+0x2bb): undefined reference to `cairo_arc'
/usr/bin/ld: cairo.c:(.text+0x2c7): undefined reference to `cairo_fill'
/usr/bin/ld: cairo.c:(.text+0x2d3): undefined reference to `cairo_destroy'
/usr/bin/ld: ./build/cairo.o: in function `draw_invisible_point':
cairo.c:(.text+0x2f2): undefined reference to `cairo_create'
/usr/bin/ld: cairo.c:(.text+0x312): undefined reference to `cairo_set_source_rgba'
/usr/bin/ld: cairo.c:(.text+0x31e): undefined reference to `cairo_paint'
/usr/bin/ld: cairo.c:(.text+0x342): undefined reference to `cairo_set_source_rgba'
/usr/bin/ld: cairo.c:(.text+0x35a): undefined reference to `cairo_set_line_width'
/usr/bin/ld: cairo.c:(.text+0x38a): undefined reference to `cairo_arc'
/usr/bin/ld: cairo.c:(.text+0x396): undefined reference to `cairo_fill'
/usr/bin/ld: cairo.c:(.text+0x3a2): undefined reference to `cairo_destroy'
/usr/bin/ld: ./build/cairo.o: in function `clear_surface':
cairo.c:(.text+0x3c1): undefined reference to `cairo_create'
/usr/bin/ld: cairo.c:(.text+0x3e1): undefined reference to `cairo_set_source_rgba'
/usr/bin/ld: cairo.c:(.text+0x3f2): undefined reference to `cairo_set_operator'
/usr/bin/ld: cairo.c:(.text+0x3fe): undefined reference to `cairo_paint'
/usr/bin/ld: cairo.c:(.text+0x40a): undefined reference to `cairo_destroy'
/usr/bin/ld: ./build/main.o: in function `main':
main.c:(.text+0x153): undefined reference to `cairo_xlib_surface_create'
/usr/bin/ld: main.c:(.text+0x16b): undefined reference to `cairo_xlib_surface_set_size'
collect2: error: ld returned 1 exit status
make: *** [Makefile:28: build] Error 1`

**Comment by jafarlihi** [comment]
Solved with PR #4
